"""
=========================================================
File: orchestrator.py

Purpose:
Workflow Controller

Responsibilities:
1. Maintain Shared State
2. Read User Question
3. Decide Workflow (Future)
4. Route Request to Correct Agent

Flow

User
  │
  ▼
Orchestrator
  │
  ▼
Knowledge Agent
=========================================================
"""

from langgraph.graph import MessagesState


# =========================================================
# Shared State
# =========================================================

class SupportState(MessagesState):

    # Tenant Identifier
    tenant_id: str = ""

    # Latest User Question
    question: str = ""

    # Retrieved Context
    context: str = ""

    # Retrieved Documents
    documents: list = []

    # Draft generated by Knowledge Agent
    draft_answer: str = ""

    # Final Answer generated by Judge Agent
    final_answer: str = ""

    # Future:
    # Which agent/tool should handle the request?
    next_agent: str = "knowledge_agent"


# =========================================================
# Orchestrator Agent
# =========================================================

def orchestrator(state: SupportState):

    print("\n📌 Orchestrator Agent Started")

    # -----------------------------------------------------
    # Read Latest User Message
    # -----------------------------------------------------

    last_message = state["messages"][-1]

    # Save latest question
    state["question"] = last_message.content

    print(f"Question : {state['question']}")

    # -----------------------------------------------------
    # Future Routing Logic
    # -----------------------------------------------------
    #
    # Future Examples:
    #
    # Password Reset
    #        │
    #        ▼
    # Knowledge Agent
    #
    # Order Status
    #        │
    #        ▼
    # Order Agent
    #
    # Refund
    #        │
    #        ▼
    # Billing Agent
    #
    # Escalation
    #        │
    #        ▼
    # Human Agent
    #
    # Currently every request goes to
    # Knowledge Agent.
    # -----------------------------------------------------

    state["next_agent"] = "knowledge_agent"

    print(f"Next Agent : {state['next_agent']}")

    print("✅ Orchestrator Agent Finished")

    return state